export const LOG_IN = '/log-in'
export const SIGN_UP = '/sign-up'

export const HOME = 'home'
export const EXPLORE = 'explore'
export const NOTIFICATIONS = 'notifications'
export const MESSAGES = 'messages'
export const BOOKMARKS = 'bookmarks'
export const LISTS = 'lists'
export const PROFILE = 'profile'
export const SEARCH = 'search'
export const RECOMENDATIONS = 'recomendations'
export const MORE = 'more'
