name: Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: | 
          yarn lint
